version: '3.7'
services:
  mysqldb:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - ./msdata:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgresdb:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
  node:
    image: node:8
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./gate-simulator:/home/node/app
    ports:
      - '9999:9999'
    command: "npm start"